environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "32"
      nodejs_version: "8.9.1"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "64"
      nodejs_version: "8.9.1"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "32"
      nodejs_version: "8.9.1"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "64"
      nodejs_version: "8.9.1"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm@5.5.1
  - npm i -g yarn
  - npm i -g vsce
  - npm install -g azure-cli
  - yarn
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -U pip
  - python --version
  - python -m easy_install -U setuptools
  - "%PYTHON%/Scripts/pip.exe install --upgrade -r requirements.txt"

test_script:
  - node --version
  - npm --version
  - npm run clean
  - npm run vscode:prepublish
  - vsce package
  - npm run testSingleWorkspace --silent
  - npm run cover:enable
  - npm run testMultiWorkspace --silent
  - npm run cover:upload
